name: orthanc-lsb # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.5.6' # just for humans, typically '1.2+git' or '1.3.2'
summary: Lightweight DICOM server for healthcare and medical research.
description: |
  Orthanc aims at providing a simple, yet powerful standalone DICOM server. 
  It is designed to improve the DICOM flows in hospitals and to support 
  research about the automated analysis of medical images. Orthanc lets 
  its users focus on the content of the DICOM files, hiding the complexity 
  of the DICOM format and of the DICOM protocol

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  orthanc:
    command: Orthanc /var/snap/orthanc-lsb/current/config_files/ --verbose
    daemon: simple
    environment:
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    plugs:
      - home
      - network
      - network-bind
  orthancrecovercompressedfile:
    command: OrthancRecoverCompressedFile

parts:
  orthanc:
    plugin: dump
    source: source
    source-type: local
    stage-packages:
      - "libgdcm-tools"

  standard-plugins:
    plugin: dump
    source: source
    source-subdir: plugins
    source-type: local
    organize:
      "*.so" : share/orthanc/plugins/

  